/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Tag = {
  _id: string;
  _type: "tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  description?: string;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type TagReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "tag";
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  author: AuthorReference;
  tags: Array<
    {
      _key: string;
    } & TagReference
  >;
  publishedAt: string;
  title: string;
  slug: Slug;
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  bio: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Tag
  | Slug
  | SanityImageAssetReference
  | AuthorReference
  | TagReference
  | Post
  | Author
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: packages/cms/queries/author.ts
// Variable: AUTHOR_QUERY
// Query: *[  _type == "author"  && slug.current == $slug][0]{  _id,  name,  slug,  image,  bio,  "posts": *[    _type == "post"    && references(^._id)    && defined(slug.current)  ]|order(publishedAt desc){    _id,    title,    slug,    publishedAt,    image  }}
export type AUTHOR_QUERY_RESULT = {
  _id: string;
  name: string;
  slug: Slug;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  bio: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  posts: Array<{
    _id: string;
    title: string;
    slug: Slug;
    publishedAt: string;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
  }>;
} | null;

// Source: packages/cms/queries/author.ts
// Variable: AUTHOR_SLUGS_QUERY
// Query: *[_type == "author" && defined(slug.current)]{"slug": slug.current}
export type AUTHOR_SLUGS_QUERY_RESULT = Array<{
  slug: string;
}>;

// Source: packages/cms/queries/author.ts
// Variable: AUTHORS_QUERY
// Query: *[  _type == "author"  && defined(slug.current)]|order(name asc){  _id,  name,  slug,  image,  "posts": *[    _type == "post"    && references(^._id)    && defined(slug.current)  ]|order(publishedAt desc){    _id,    title,    slug,    publishedAt  }}
export type AUTHORS_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  slug: Slug;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  posts: Array<{
    _id: string;
    title: string;
    slug: Slug;
    publishedAt: string;
  }>;
}>;

// Source: packages/cms/queries/post.ts
// Variable: POST_QUERY
// Query: *[_type == "post" && slug.current == $slug][0]{  ...,  author->{name, slug, image},  tags[]->{_id, title, slug}}
export type POST_QUERY_RESULT = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  author: {
    name: string;
    slug: Slug;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
  };
  tags: Array<{
    _id: string;
    title: string;
    slug: Slug;
  }>;
  publishedAt: string;
  title: string;
  slug: Slug;
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
} | null;

// Source: packages/cms/queries/post.ts
// Variable: POSTS_QUERY
// Query: *[ _type == "post" && defined(slug.current)]|order(publishedAt desc)[0...12]{_id, title, slug, publishedAt, image, author->{name, slug, image}, tags[]->{_id, title, slug}}
export type POSTS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: Slug;
  publishedAt: string;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  author: {
    name: string;
    slug: Slug;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
  };
  tags: Array<{
    _id: string;
    title: string;
    slug: Slug;
  }>;
}>;

// Source: packages/cms/queries/post.ts
// Variable: POST_SLUGS_QUERY
// Query: *[_type == "post" && defined(slug.current)]{"slug": slug.current}
export type POST_SLUGS_QUERY_RESULT = Array<{
  slug: string;
}>;

// Source: packages/cms/queries/tag.ts
// Variable: TAG_QUERY
// Query: *[  _type == "tag"  && slug.current == $slug][0]{  _id,  title,  slug,  description,  "posts": *[    _type == "post"    && references(^._id)    && defined(slug.current)  ]|order(publishedAt desc){    _id,    title,    slug,    publishedAt,    image,    author->{name, slug, image}  }}
export type TAG_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: Slug;
  description: string | null;
  posts: Array<{
    _id: string;
    title: string;
    slug: Slug;
    publishedAt: string;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    author: {
      name: string;
      slug: Slug;
      image: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      };
    };
  }>;
} | null;

// Source: packages/cms/queries/tag.ts
// Variable: TAG_SLUGS_QUERY
// Query: *[_type == "tag" && defined(slug.current)]{"slug": slug.current}
export type TAG_SLUGS_QUERY_RESULT = Array<{
  slug: string;
}>;

// Source: packages/cms/queries/tag.ts
// Variable: TAGS_QUERY
// Query: *[  _type == "tag"  && defined(slug.current)]|order(title asc){  _id,  title,  slug,  description,  "postCount": count(*[_type == "post" && references(^._id)])}
export type TAGS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: Slug;
  description: string | null;
  postCount: number;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[\n  _type == "author"\n  && slug.current == $slug\n][0]{\n  _id,\n  name,\n  slug,\n  image,\n  bio,\n  "posts": *[\n    _type == "post"\n    && references(^._id)\n    && defined(slug.current)\n  ]|order(publishedAt desc){\n    _id,\n    title,\n    slug,\n    publishedAt,\n    image\n  }\n}': AUTHOR_QUERY_RESULT;
    '*[_type == "author" && defined(slug.current)]{"slug": slug.current}': AUTHOR_SLUGS_QUERY_RESULT;
    '*[\n  _type == "author"\n  && defined(slug.current)\n]|order(name asc){\n  _id,\n  name,\n  slug,\n  image,\n  "posts": *[\n    _type == "post"\n    && references(^._id)\n    && defined(slug.current)\n  ]|order(publishedAt desc){\n    _id,\n    title,\n    slug,\n    publishedAt\n  }\n}': AUTHORS_QUERY_RESULT;
    '*[_type == "post" && slug.current == $slug][0]{\n  ...,\n  author->{name, slug, image},\n  tags[]->{_id, title, slug}\n}': POST_QUERY_RESULT;
    '*[ _type == "post" && defined(slug.current)]|order(publishedAt desc)[0...12]{_id, title, slug, publishedAt, image, author->{name, slug, image}, tags[]->{_id, title, slug}}': POSTS_QUERY_RESULT;
    '*[_type == "post" && defined(slug.current)]{"slug": slug.current}': POST_SLUGS_QUERY_RESULT;
    '*[\n  _type == "tag"\n  && slug.current == $slug\n][0]{\n  _id,\n  title,\n  slug,\n  description,\n  "posts": *[\n    _type == "post"\n    && references(^._id)\n    && defined(slug.current)\n  ]|order(publishedAt desc){\n    _id,\n    title,\n    slug,\n    publishedAt,\n    image,\n    author->{name, slug, image}\n  }\n}': TAG_QUERY_RESULT;
    '*[_type == "tag" && defined(slug.current)]{"slug": slug.current}': TAG_SLUGS_QUERY_RESULT;
    '*[\n  _type == "tag"\n  && defined(slug.current)\n]|order(title asc){\n  _id,\n  title,\n  slug,\n  description,\n  "postCount": count(*[_type == "post" && references(^._id)])\n}': TAGS_QUERY_RESULT;
  }
}
