// packages/ui/components/app-icons

import {
  ApertureIcon,
  ArchiveIcon,
  ArrowDownIcon,
  ArrowLeftIcon,
  ArrowLeftRightIcon,
  ArrowRightIcon,
  ArrowUpDownIcon,
  ArrowUpIcon,
  ArrowUpRightIcon,
  AudioWaveformIcon,
  BarChartIcon,
  BellIcon,
  BoldIcon,
  BookOpenIcon,
  Building2Icon,
  CalendarIcon,
  CaptionsIcon,
  CheckCircle2Icon,
  CheckIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronsLeftRightIcon,
  ChevronsUpDownIcon,
  ChevronUpIcon,
  CircleCheckIcon,
  CircleIcon,
  ClockIcon,
  CloudIcon,
  Code2Icon,
  CopyIcon,
  CreditCardIcon,
  CrownIcon,
  DatabaseIcon,
  DownloadIcon,
  ExternalLinkIcon,
  EyeIcon,
  EyeOffIcon,
  FileIcon,
  FilePlusIcon,
  FileTextIcon,
  FilterIcon,
  FolderIcon,
  FolderOpenIcon,
  FolderPlusIcon,
  FolderTreeIcon,
  GlobeIcon,
  GripHorizontalIcon,
  GripVerticalIcon,
  Heading2Icon,
  HomeIcon,
  ImageIcon,
  InfoIcon,
  ItalicIcon,
  LanguagesIcon,
  LayoutDashboardIcon,
  LifeBuoyIcon,
  Link2Icon,
  ListIcon,
  ListMusicIcon,
  ListOrderedIcon,
  Loader2Icon,
  LockIcon,
  LockOpenIcon,
  LogInIcon,
  LogOutIcon,
  MailIcon,
  Maximize2Icon,
  MenuIcon,
  MessageSquareIcon,
  MinusIcon,
  MonitorIcon,
  MoonIcon,
  MoreHorizontalIcon,
  MoreVerticalIcon,
  MoveDownIcon,
  MoveLeftIcon,
  MoveRightIcon,
  MoveUpIcon,
  MusicIcon,
  OctagonXIcon,
  PanelLeftIcon,
  PanelRightIcon,
  PauseIcon,
  PencilIcon,
  PhoneCallIcon,
  PieChartIcon,
  PlayIcon,
  PlusIcon,
  RefreshCwIcon,
  Repeat1Icon,
  RepeatIcon,
  SearchIcon,
  SendIcon,
  Settings2Icon,
  Share2Icon,
  ShieldCheckIcon,
  ShieldIcon,
  ShuffleIcon,
  SkipBackIcon,
  SkipForwardIcon,
  SparkleIcon,
  StarIcon,
  StrikethroughIcon,
  SunIcon,
  Trash2Icon,
  TriangleAlertIcon,
  UploadCloudIcon,
  UserIcon,
  UserMinusIcon,
  UserPlusIcon,
  UsersIcon,
  VideoIcon,
  Volume1Icon,
  Volume2Icon,
  VolumeXIcon,
  WorkflowIcon,
  WrenchIcon,
  XIcon,
} from "lucide-react";
import type { SVGProps } from "react";
import {
  FaDropbox,
  FaFacebook,
  FaGoogle,
  FaGoogleDrive,
  FaLinkedin,
  FaMicrosoft,
  FaYoutube,
} from "react-icons/fa";

export type { LucideIcon } from "lucide-react";
// biome-ignore lint/performance/noBarrelFile: single deliberate re-export, not a full barrel — satisfies noExportedImports' "use export from" fix.
export { icons } from "lucide-react";

/** Dropbox brand glyph — lucide dropped brand icons, so this is the official
 * mark (simple-icons, viewBox 0 0 24 24, filled). Sized by `className` like
 * any lucide icon (e.g. `size-4`). */
function DropboxIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      aria-hidden="true"
      fill="currentColor"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <path d="M6 1.807L0 5.629l6 3.822 6.001-3.822L6 1.807zM18 1.807l-6 3.822 6 3.822 6-3.822-6-3.822zM0 13.274l6 3.822 6.001-3.822L6 9.452l-6 3.822zM18 9.452l-6 3.822 6 3.822 6-3.822-6-3.822zM6 18.371l6.001 3.822 6-3.822-6-3.822L6 18.371z" />
    </svg>
  );
}

export const AppIcons = {
  Common: {
    Analytics: BarChartIcon,
    Bell: BellIcon,
    Check: CheckIcon,
    Document: FileTextIcon,
    File: FileIcon,
    FilePlus: FilePlusIcon,
    Home: HomeIcon,
    Image: ImageIcon,
    Info: InfoIcon,
    Loader: Loader2Icon,
    Menu: MenuIcon,
    Minus: MinusIcon,
    Music: MusicIcon,
    Plus: PlusIcon,
    Refresh: RefreshCwIcon,
    Trash: Trash2Icon,
    Upload: UploadCloudIcon,
    Video: VideoIcon,
    Waveform: AudioWaveformIcon,
    X: XIcon,
  },
  Directional: {
    ArrowDown: ArrowDownIcon,
    ArrowLeft: ArrowLeftIcon,
    ArrowLeftRight: ArrowLeftRightIcon,
    ArrowRight: ArrowRightIcon,
    ArrowUp: ArrowUpIcon,
    ArrowUpDown: ArrowUpDownIcon,
    ArrowUpRight: ArrowUpRightIcon,
    ChevronDown: ChevronDownIcon,
    ChevronLeft: ChevronLeftIcon,
    ChevronRight: ChevronRightIcon,
    ChevronsLeftRight: ChevronsLeftRightIcon,
    ChevronsUpDown: ChevronsUpDownIcon,
    ChevronUp: ChevronUpIcon,
    MoveDown: MoveDownIcon,
    MoveLeft: MoveLeftIcon,
    MoveRight: MoveRightIcon,
    MoveUp: MoveUpIcon,
  },
  Media: {
    Download: DownloadIcon,
    Pause: PauseIcon,
    Play: PlayIcon,
    Playlist: ListMusicIcon,
    Repeat: RepeatIcon,
    RepeatOne: Repeat1Icon,
    Shuffle: ShuffleIcon,
    SkipBack: SkipBackIcon,
    SkipForward: SkipForwardIcon,
    VolumeHigh: Volume2Icon,
    VolumeLow: Volume1Icon,
    VolumeMuted: VolumeXIcon,
    Waveform: AudioWaveformIcon,
  },
  OneOff: {
    Aperture: ApertureIcon,
    Archive: ArchiveIcon,
    Bell: BellIcon,
    BookOpen: BookOpenIcon,
    Building: Building2Icon,
    Buoy: LifeBuoyIcon,
    Calendar: CalendarIcon,
    Captions: CaptionsIcon,
    CheckCircle: CheckCircle2Icon,
    Circle: CircleIcon,
    CircleCheck: CircleCheckIcon,
    Clock: ClockIcon,
    Cloud: CloudIcon,
    Code: Code2Icon,
    Copy: CopyIcon,
    CreditCard: CreditCardIcon,
    Crown: CrownIcon,
    Dashboard: LayoutDashboardIcon,
    Database: DatabaseIcon,
    Dropbox: DropboxIcon,
    EllipsisHorizontal: MoreHorizontalIcon,
    EllipsisVertical: MoreVerticalIcon,
    ExternalLink: ExternalLinkIcon,
    Eye: EyeIcon,
    EyeOff: EyeOffIcon,
    Filter: FilterIcon,
    Folder: FolderIcon,
    FolderOpen: FolderOpenIcon,
    FolderPlus: FolderPlusIcon,
    FolderTree: FolderTreeIcon,
    Globe: GlobeIcon,
    GripHorizontal: GripHorizontalIcon,
    GripVertical: GripVerticalIcon,
    Languages: LanguagesIcon,
    Link: Link2Icon,
    Lock: LockIcon,
    LockOpen: LockOpenIcon,
    LogIn: LogInIcon,
    LogOut: LogOutIcon,
    Mail: MailIcon,
    Maximize: Maximize2Icon,
    MessageSquare: MessageSquareIcon,
    Minus: MinusIcon,
    Monitor: MonitorIcon,
    Moon: MoonIcon,
    OctagonX: OctagonXIcon,
    Pencil: PencilIcon,
    PhoneCall: PhoneCallIcon,
    PieChart: PieChartIcon,
    Search: SearchIcon,
    Send: SendIcon,
    Settings: Settings2Icon,
    Share: Share2Icon,
    Shield: ShieldIcon,
    ShieldCheck: ShieldCheckIcon,
    SidebarLeft: PanelLeftIcon,
    SidebarRight: PanelRightIcon,
    Star: StarIcon,
    Sun: SunIcon,
    TriangleAlert: TriangleAlertIcon,
    User: UserIcon,
    UserMinus: UserMinusIcon,
    UserPlus: UserPlusIcon,
    Users: UsersIcon,
    Workflow: WorkflowIcon,
  },
  Socials: {
    Dropbox: FaDropbox,
    Facebook: FaFacebook,
    Google: FaGoogle,
    GoogleDrive: FaGoogleDrive,
    Linkedin: FaLinkedin,
    Microsoft: FaMicrosoft,
    Youtube: FaYoutube,
  },
  Text: {
    Bold: BoldIcon,
    Heading2: Heading2Icon,
    Italic: ItalicIcon,
    List: ListIcon,
    ListOrdered: ListOrderedIcon,
    Strikethrough: StrikethroughIcon,
  },
  UI: {
    Sparkles: SparkleIcon,
    Wrench: WrenchIcon,
  },
} as const;
